import time

print ("Wer hört alles und sagt nichts?")
time.sleep (10)
print ("Bei welchem Brand ist kein Feuer beteiligt?")
time.sleep (10)
print ("Was wird immer kürzer, je länger man daran zieht?")
time.sleep (10)
print ("Was liegt zwischen Meer und Land?")
time.sleep (10)
print ("Warum sind Türken die nettesten Menschen der Welt?")
time.sleep (10)
print ("Was wird beim Trocknen nass?")
time.sleep (10)
print ("Welche Sprache wirst du niemals zu hören bekommen?")
time.sleep (10)
print ("Wie viele male kann man die 1 von der 20 abziehen?")
time.sleep (10)
print ("In welchen Zug passt nur ein Mensch?")
time.sleep (10)
print ("Wie machen Igel Liebe?")
time.sleep (10)

print ("Zeit vorbei")
